# Generated by Django 5.1.7 on 2025-04-04 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('CALZADO', 'Calzado'), ('ROPA', 'Ropa'), ('ACCESORIOS', 'Accesorios'), ('EQUIPACION', 'Equipación'), ('BOTINES', 'Botines')], help_text='Ej: Calzado, Ropa, Accesorios', max_length=50, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción detallada del producto', null=True, verbose_name='Descripción'),
        ),
    ]
