# Generated by Django 5.2 on 2025-04-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_producto_categoria_alter_producto_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título del Banner')),
                ('imagen', models.ImageField(help_text='Usa imágenes en formato HD (16:9)', upload_to='banners/', verbose_name='Imagen (1920x1080 px)')),
                ('url_destino', models.URLField(blank=True, help_text='Ej: /ofertas/ o https://tudominio.com/promocion', verbose_name='URL al hacer clic')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['orden'],
            },
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('CAMISETAS', 'Camisetas'), ('SUDADERAS', 'Sudaderas'), ('ACCESORIOS', 'Accesorios')], help_text='Ej: Camisetas, Sudaderas, Accesorios', max_length=50, verbose_name='Categoría'),
        ),
    ]
